"""New

Revision ID: 74247378a249
Revises: 
Create Date: 2022-09-21 12:33:11.985036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74247378a249'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cars_data',
    sa.Column('car_id', sa.String(length=6), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('owner', sa.String(length=11), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cars_data')
    # ### end Alembic commands ###
